import { title } from "process";

// app/layout.js or app/layout.tsx
export const metadata = {
  title:{
    default:"Hello some one",
    template:"%s -MinooDev",
    absolute:""
  },
  // title: "Hello",

  descrepion: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* -------------header---------------- */}
        <header
          style={{
            backgroundColor: "red",
            color: "white",
            textAlign: "center",
            fontSize: 20,
          }}
        >
          <p>سربرگ</p>
        </header>
        {children} {/* This will render the About page or any other page */}
        {/* -------------footer------------------ */}
        <footer
          style={{
            backgroundColor: "blue",
            color: "white",
            textAlign: "center",
            fontSize: 20,
          }}
        >
          <p>پاورقی</p>
        </footer>
      </body>
    </html>
  );
}
